export const CabinetState = Object.freeze({
  OPEN: "OPEN",

  DELIVERY_PARCEL_EXIST: "DELIVERY_PARCEL_EXIST",

  DISTRIBUTE_PARCEL_EXIST: "DISTRIBUTE_PARCEL_EXIST",

  PICKUP_PARCEL_EXIST: "PICKUP_PARCEL_EXIST"
});
